export { default as DefaultLayout } from './DefaultLayout'
export { default as HomeLayout } from './HomeLayout'
export { default as QrPayLayout } from './QrPayLayout'
export { default as HotelierLayout } from './HotelierLayout'
export { default as ManageAdminLayout } from './Admin/ManageLayout'
export { default as HomeAdminLayout } from './Admin/HomeLayoutAdmin'
